### ISSUE TITLE
Registering with Eureka discovery server working, but renew failing.

### ISSUE THREAD

**Issue by mries92** [SteeltoeOSS/Discovery#46]
Hello, I am experiencing a weird issue with the Steeltoe discovery client. I have an instance of a Eureka server stood up in PCF, and have followed the Fortune-Teller examples for connecting to this registry. The connection works fine, and I can see the service being registered and listed on the 'Manage' page of the discovery service. After a little while though, usually about 30 seconds to 2 minutes, the service de-registers itself and I see the following in the logs on PCF.

> 2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] at System.Threading.Tasks.ValueTask`1.get_Result()
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] at Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient.SendHeartBeatAsync(String appName, String id, InstanceInfo info, InstanceStatus overriddenStatus)
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] at Steeltoe.Discovery.Eureka.DiscoveryClient.RenewAsync()
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] [40m[37mdbug[39m[22m[49m: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] Renew failed
2018-10-29T13:02:46.276-04:00 [APP/PROC/WEB/0] [OUT] HeartBeat failed

Here is my appsettings.json

`{
    "Logging": {
        "LogLevel": {
            "Default": "Warning"
        }
    },
    /* Spring options for steeltoe compatibility */
    "spring": {
        "application": {
            "name": "message-generator-core"
        },
        "cloud": {
            "discovery": {
                "registrationMethod": "direct"
            }
        }
    },
    /* Configure the connection to the eureka discovery service. */
    "eureka": {
        "client": {
            "serviceUrl": "http://localhost:8761/eureka/",
            "shouldFetchRegistry": false
        },
        "instance": {
            "port": 5000,
            "securePortEnabled": true
        }
    }
}`

If anybody has any idea what may be causing this, I would greatly appreciate any insight! If you need any more info from me, please let me know.

**Comment by TimHess** [comment]
Hi @mries92 

Are you running one of the Steeltoe samples, or a different app that is based on one of them?

It looks like the actual exception is missing from your stack trace there, could you include a bit more of the logs please?
If you are not running one of the Steeltoe samples, please share which versions of [ASP].NET [Core] and Steeltoe you're running?

**Comment by mries92** [comment]
@TimHess

Hey Tim, Thanks for the reply. This is a separate app that is based off the Steeltoe samples. We are on ASP.NET Core version 2.1.1, and Steeltoe 2.1.1. Here is a more complete stack trace from when the appplication starts to when the error ocurrs. From this point, it is just the same error about the renew failed over and over again.

> 2018-10-29T16:26:18.978-04:00 [CELL/0] [OUT] Starting health monitoring of container
2018-10-29T16:26:19.860-04:00 [APP/PROC/WEB/0] [OUT] [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
2018-10-29T16:26:19.860-04:00 [APP/PROC/WEB/0] [OUT] User profile is available. Using '/home/vcap/app/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
2018-10-29T16:26:19.885-04:00 [APP/PROC/WEB/0] [OUT] [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
2018-10-29T16:26:19.885-04:00 [APP/PROC/WEB/0] [OUT] Creating key {d082b9cf-31de-4222-805f-879d478b45ef} with creation date 2018-10-29 20:26:19Z, activation date 2018-10-29 20:26:19Z, and expiration date 2019-01-27 20:26:19Z.
2018-10-29T16:26:19.903-04:00 [APP/PROC/WEB/0] [OUT] [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
2018-10-29T16:26:19.903-04:00 [APP/PROC/WEB/0] [OUT] No XML encryptor configured. Key {d082b9cf-31de-4222-805f-879d478b45ef} may be persisted to storage in unencrypted form.
2018-10-29T16:26:19.909-04:00 [APP/PROC/WEB/0] [OUT] [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
2018-10-29T16:26:19.909-04:00 [APP/PROC/WEB/0] [OUT] Writing data to file '/home/vcap/app/.aspnet/DataProtection-Keys/key-d082b9cf-31de-4222-805f-879d478b45ef.xml'.
2018-10-29T16:26:20.617-04:00 [APP/PROC/WEB/0] [OUT] [40m[37mdbug[39m[22m[49m: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
2018-10-29T16:26:20.617-04:00 [APP/PROC/WEB/0] [OUT] GetRequestContent generated JSON: {"instance":{"instanceId":"10.255.118.35:a0f93b12-c308-4f6c-7fda-675e","app":"MESSAGE-GENERATOR-CORE","appGroupName":null,"ipAddr":"****","sid":"na","port":{"@enabled":true,"$":8080},"securePort":{"@enabled":true,"$":8080},"homePageUrl":"http://****:8080/","statusPageUrl":"http://****:8080/info","healthCheckUrl":"http://****:8080/health","secureHealthCheckUrl":null,"vipAddress":"message-generator-core","secureVipAddress":"message-generator-core","countryId":1,"dataCenterInfo":{"@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo","name":"MyOwn"},"hostName":"****","status":"UP","overriddenstatus":"UNKNOWN","leaseInfo":{"renewalIntervalInSecs":30,"durationInSecs":90,"registrationTimestamp":0,"lastRenewalTimestamp":0,"renewalTimestamp":0,"evictionTimestamp":0,"serviceUpTimestamp":0},"isCoordinatingDiscoveryServer":false,"metadata":{"cfAppGuid":"c9d55dcc-f84c-4f32-b624-c670542cda22","cfInstanceIndex":"0","instanceId":"a0f93b12-c308-4f6c-7fda-675e","zone":"unknown"},"lastUpdatedTimestamp":1540844779999,"lastDirtyTimestamp":1540844779999,"actionType":"ADDED"}}
2018-10-29T16:26:20.655-04:00 [APP/PROC/WEB/0] [OUT] [40m[37mdbug[39m[22m[49m: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
2018-10-29T16:26:20.655-04:00 [APP/PROC/WEB/0] [OUT] RegisterAsync https://eureka-a51cd99a-1bd9-4883-92fb-71abb8c0d4d1.apps.dt-pcf-adc.duke-energy.com/eureka/apps/MESSAGE-GENERATOR-CORE, status: NoContent
2018-10-29T16:26:20.658-04:00 [APP/PROC/WEB/0] [OUT] [40m[37mdbug[39m[22m[49m: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
2018-10-29T16:26:20.658-04:00 [APP/PROC/WEB/0] [OUT] Register MESSAGE-GENERATOR-CORE/10.255.118.35:a0f93b12-c308-4f6c-7fda-675e returned: NoContent
2018-10-29T16:26:20.658-04:00 [APP/PROC/WEB/0] [OUT] [40m[32minfo[39m[22m[49m: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
2018-10-29T16:26:20.658-04:00 [APP/PROC/WEB/0] [OUT] Starting HeartBeat
2018-10-29T16:26:20.941-04:00 [APP/PROC/WEB/0] [OUT] Hosting environment: Development
2018-10-29T16:26:20.941-04:00 [APP/PROC/WEB/0] [OUT] Content root path: /home/vcap/app
2018-10-29T16:26:20.941-04:00 [APP/PROC/WEB/0] [OUT] Now listening on: http://0.0.0.0:8080
2018-10-29T16:26:20.941-04:00 [APP/PROC/WEB/0] [OUT] Application started. Press Ctrl+C to shut down.
2018-10-29T16:26:21.241-04:00 [CELL/0] [OUT] Container became healthy
2018-10-29T16:26:27.385-04:00 [CELL/0] [OUT] Cell e3130413-33d2-4128-8597-a683dd5a6907 destroying container for instance f2e7c258-6275-4f9c-78bf-da4c
2018-10-29T16:26:27.714-04:00 [CELL/0] [OUT] Cell e3130413-33d2-4128-8597-a683dd5a6907 successfully destroyed container for instance f2e7c258-6275-4f9c-78bf-da4c
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] [41m[30mfail[39m[22m[49m: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] SendHeartBeatAsync Failed
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] System.Net.Http.HttpRequestException: No such device or address ---> System.Net.Sockets.SocketException: No such device or address
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] --- End of inner exception stack trace ---
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] at System.Threading.Tasks.ValueTask`1.get_Result()
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2018-10-29T16:26:50.730-04:00 [APP/PROC/WEB/0] [OUT] at Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient.SendHeartBeatAsync(String appName, String id, InstanceInfo info, InstanceStatus overriddenStatus)
2018-10-29T16:26:50.733-04:00 [APP/PROC/WEB/0] [OUT] [41m[30mfail[39m[22m[49m: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
2018-10-29T16:26:50.733-04:00 [APP/PROC/WEB/0] [OUT] Renew Failed
2018-10-29T16:26:50.733-04:00 [APP/PROC/WEB/0] [OUT] System.Net.Http.HttpRequestException: No such device or address ---> System.Net.Sockets.SocketException: No such device or address
2018-10-29T16:26:50.733-04:00 [APP/PROC/WEB/0] [OUT] at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
2018-10-29T16:26:50.733-04:00 [APP/PROC/WEB/0] [OUT]
--- End of inner exception stack trace ---

I have replaced the ip addresses with placeholders.

**Comment by TimHess** [comment]
What stack are you deploying the app to? (eg: windows2012R2, windows2016, cflinuxfs2, cflinuxfs3)
Can you confirm that DNS is working reliably in the cell you're deploying to?
Have you tried deploying one of the Steeltoe Discovery samples onto your infrastructure to make sure that it isn't an environmental issue?

`No such device or address` typically means either DNS has failed, or you've made a request to a bad server address. Considering that it can succeed, I don't think the address is likely to be bad.  Does it successfully register every time your restart the app?
Configuring the log level for Steeltoe to Debug or Trace could provide some additional information.

**Comment by TimHess** [comment]
Two more things to try, in addition to deploying the Steeltoe samples - 

1. I pushed a new release of Discovery to the [dev feed](https://www.myget.org/F/steeltoedev/api/v3/index.json) that logs the url when the request fails, so we can at least rule out any surprises there - the version is '2.2.0-dev-287'
1. Possibly a long shot, but [opt out of the SocketsHttpHandler](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.0.md#networking-performance) that shipped with .NET Core 2.1 might give us other ideas if the results change

**Comment by mries92** [comment]
Hey Tim,

Just an update on the situation. Today I tried building and deploying the Fortune-Teller samples for circuit breaker again. I can confirm the exact same behavior we saw with our services. They sporadically succeed at registering with the Eureka server, but are dropped when the renew is attempted.

When adding the flag mentioned previously to the example services Program.cs, the register works successfully. However, this doesn't solve everything. Although the service registers successfully and it is listed in the Eureka management console, we are unable to hit the service by referencing it by name. We are still able to hit the java services by name however.

**Comment by TimHess** [comment]
`we are unable to hit the service by referencing it by name` - does that mean you're still seeing exceptions that appear to be DNS related, but only in .NET apps?

Its interesting that opting out of `SocketsHttpHandler` would resolve some, but no all instances of the issue

**Comment by mries92** [comment]
That is correct. Using the same Eureka instance for both .NET and Java apps, the Java apps are discoverable by name but the .NET ones are not. Interestingly, we can hit the Java services by name from the .NET services, but not vice-versa. So it seems the fetch registry is working on the .NET side, just not the actual registration (even though it says it registers successfully and appears in the management console).

As you mentioned, I find it strange that SocketsHttpHandler fixes some issues, and causes others. I have talked with our cloud team and they are not sure what is causing the problem. It seems like it may be unique to our instance of PCF, which might make this issue hard to track down.

**Comment by jkonicki** [comment]
Closing this issue.  If this is still an issue please reopen under the `steeltoe` repository.
