### ISSUE TITLE
DiscoveryManager.Instance.Initialize(clientConfig) NullReferenceException

### ISSUE THREAD

**Issue by safari137** [SteeltoeOSS/Discovery#5]
I have the following code as I followed the readme on https://github.com/SteeltoeOSS/Discovery/tree/master/src/Steeltoe.Discovery.Eureka.Client

        ```
private IEurekaClient _client;

        public DiscoveryService()
        {
            // If there is not valid client, initialize it
            if (DiscoveryManager.Instance.Client == null)
                this.Init();

            this._client = DiscoveryManager.Instance.Client;
        }

        private void Init()
        {
            // Discovery Url
            EurekaClientConfig clientConfig = new EurekaClientConfig()
            {
                EurekaServerServiceUrls = "https://localhost:8080/eureka/"
            };

            // Initialize client
            // No services to register, we're only getting data
            DiscoveryManager.Instance.Initialize(clientConfig);
        }
```

When I run the code I get the following exception:

{"Object reference not set to an instance of an object."}

Here is the StackTrace:
   at Steeltoe.Discovery.Eureka.DiscoveryClient..ctor(IEurekaClientConfig clientConfig, IEurekaHttpClient httpClient, ILoggerFactory logFactory)
   at Steeltoe.Discovery.Eureka.DiscoveryManager.Initialize(IEurekaClientConfig clientConfig, IEurekaHttpClient httpClient, ILoggerFactory logFactory)
   at Steeltoe.Discovery.Eureka.DiscoveryManager.Initialize(IEurekaClientConfig clientConfig, ILoggerFactory logFactory)
   at DiscoveryService.DiscoveryService.Init() in *****
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)

**Comment by dtillman** [comment]
Sorry for late reply, thanks for reporting issue.  
The problem you found is that the default setting for EurekaClientConfig.ShouldRegisterWithEureka is true.  
Since you didn't change that, the client tried to register but didn't have any InstanceInfo to register with and it hit the Null Pointer problem.  I added an additional check to fix this and I will update the documentation as well.
Thanks
Dave
