### ISSUE TITLE
DoGetApplicationsAsync Failed

### ISSUE THREAD

**Issue by Rynaret** [SteeltoeOSS/Discovery#53]
When a service is registered without instanceId I have following error

```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.set_Item(TKey key, TValue value)
   at Steeltoe.Discovery.Eureka.AppInfo.Application.FromJsonApplication(JsonApplication japp)
   at Steeltoe.Discovery.Eureka.AppInfo.Applications.FromJsonApplications(JsonApplications japps)
   at Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient.DoGetApplicationsAsync(String path, ISet`1 regions)
```

**Comment by Rynaret** [comment]
#54

**Comment by jkonicki** [comment]
PR was merged. Closing issue
