### ISSUE TITLE
Fetch registry Object reference not set EurekaPostConfigurer.UpdateWithDefaultsForRoute

### ISSUE THREAD

**Issue by thnk2wn** [SteeltoeOSS/Discovery#58]
- Using Steeltoe.Discovery.ClientCore Version "2.2.0" 
- Attempting to fetch registry from a .net core 2.2 console app linux x64 on stack cflinuxfs2

When I attempt to resolve `IDiscoveryClient` type I get the error `Object reference not set to an instance of an object.` error in `Steeltoe.Discovery.Eureka.EurekaPostConfigurer.UpdateWithDefaultsForRoute`. The full call stack follows.

<pre>
2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Steeltoe.Discovery.Eureka.EurekaPostConfigurer.UpdateWithDefaultsForRoute(EurekaServiceInfo si, EurekaInstanceOptions instOptions)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at System.Lazy`1.CreateValue()
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Steeltoe.Discovery.Eureka.EurekaApplicationInfoManager..ctor(IOptionsMonitor`1 instConfig, ILoggerFactory logFactory)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR --- End of stack trace from previous location where exception was thrown ---
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.<>c.<AddEurekaServices>b__12_0(IServiceProvider p)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at RiverFlowProcessor.Startup.UseDiscoveryClient() in C:\Source\Tools\river-flow-processor\consumer\Startup.cs:line 71
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at RiverFlowProcessor.Startup.Configure() in C:\Source\Tools\river-flow-processor\consumer\Startup.cs:line 45
   2019-03-20T20:56:31.52-0700 [APP/PROC/WEB/0] ERR    at RiverFlowProcessor.Program.Main(String[] args) in C:\Source\Tools\river-flow-processor\consumer\Program.cs:line 23
</pre>

The consumer sample I'm using is at https://github.com/thnk2wn/pcf-river-flow-processor/tree/master/consumer with [Startup ](https://github.com/thnk2wn/pcf-river-flow-processor/blob/master/consumer/Startup.cs) and appSettings*.json being the main files of interest (targeting environment Development).

The API side it's attempting to reach is at https://github.com/thnk2wn/pcf-river-flow-processor/tree/master/api and everything from logging and the Apps Manager service registry dashboard seem to indicate that side is fine.

Using `cf env` on both consumer and API sides both show `p-service-registry` set as expected in `VCAP_SERVICES`.

Locally it seemed to be working okay on the fetch side before but not in my PCF instance.

I've reviewed the samples and tried various things. My use case is slightly different as it is a console app but it is using the built-in DI/IOC like a web app but can't use the webhost specific methods in Steeltoe since it isn't a web app and web references aren't desirable there.

Digging through the code but not quite sure what object is null that it's expecting to be set. 

Questions:

- Ideas to what the problem might be?
- Can the error handling be improved to offer a better indication of what's not set or what the problem might be?

**Comment by thnk2wn** [comment]
Created a one line PR #65 to address this. There is also a branch [steeltoe-discovery-debug](https://github.com/thnk2wn/pcf-river-flow-processor/tree/steeltoe-discovery-debug) in my repo mentioned above where all the Steeltoe nuget packages are replaced with source project references to debug and address the issue.

**Comment by dlane771** [comment]
I am experiencing exactly the same issue. However we are using a .NET Core 2.2 console application that previously worked a few days ago and now it doesn't work and we are getting exactly the same error. I did note that the Dotnet-Core Buildpack changed versions from 2.2.5 to 2.2.7, however the PCF platform could have changed as well.
