### ISSUE TITLE
Running with Consul Throws CheckID does not have associated TTL

### ISSUE THREAD

**Issue by sorvis** [SteeltoeOSS/Discovery#72]
Hello,

I'm testing out discovery with Consul. I have setup my application like this:

Nuget:
```
<PackageReference Include="Steeltoe.Discovery.ClientCore" Version="2.2.0" />
<PackageReference Include="Steeltoe.Management.CloudFoundry" Version="1.1.0" />
```

Startup.cs
```
public void ConfigureApplication(IApplicationBuilder app, IHostingEnvironment env, IApplicationLifetime applicationLifetime)
{
    app.UseDiscoveryClient();
}

public void ConfigureServices(IServiceCollection services, IConfigurationRoot config)
{
    services.AddDiscoveryClient(config);
}
```

appsettings.json
```
"consul": {
    "host": "localhost",
    "ttl":  "5",
    "discovery": {
      "serviceName": "Test",
      "healthCheckUrl": "/health",
      "heartbeat:enabled": true,
      "heartbeat:ttlValue": "5"
    }
  },
```

Started docker instance of consul with:
```
docker run -p 8500:8500 -d --name=dev-consul consul
```

Then when I start my application I get this error message:

> Consul.ConsulRequestException
>   HResult=0x80131500
>   Message=Unexpected response, status code InternalServerError: CheckID "service:Test-1128208441" does not have associated TTL
>   Source=Consul
>   StackTrace:
>    at Consul.PutNothingRequest.<Execute>d__5.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Steeltoe.Discovery.Consul.Discovery.TtlScheduler.<<Add>b__11_0>d.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> 

Am I missing some configuration?

**Comment by dtillman** [comment]
Maybe try this instead: 

"consul": {
    "host": "localhost",
    "ttl":  "5",
    "discovery": {
      "serviceName": "Test",
      "healthCheckUrl": "/health",
      "heartbeat": {
          "enabled": true,
         "ttlValue": 5
      }
    }
  },

**Comment by sorvis** [comment]
@dtillman thank you for the response. I gave that a try now I'm seeing this error. Do I have to specificy that Consul should be used for discovery someplace?

> {System.ArgumentException: Discovery client type UNKNOWN, check configuration
>    at Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.AddDiscoveryServices(IServiceCollection services, IServiceInfo info, IConfiguration config, IDiscoveryLifecycle lifecycle)
>    at Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.AddDiscoveryClient(IServiceCollection services, IConfiguration config, IDiscoveryLifecycle lifecycle)
>    at Scriptmed.Skeleton.ServicesHost.ServiceDiscoveryConfig.ConfigureServices(IServiceCollection services, IConfigurationRoot config) in E:\git\SMCloud\Skeleton.Service\src\Scriptmed.Skeleton.ServicesHost\Startup.cs:line 65}
